"""Initial migration

Revision ID: 30bf72f572ce
Revises: 
Create Date: 2025-11-29 09:44:56.963320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30bf72f572ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_messages_conversation_time'))

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_participants_conversation'))
        batch_op.drop_index(batch_op.f('idx_participants_user'))
        batch_op.drop_constraint(batch_op.f('participants_conversation_id_user_id_key'), type_='unique')
        batch_op.create_unique_constraint('uq_participants_conversation_user', ['conversation_id', 'user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participants_conversation_user', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('participants_conversation_id_user_id_key'), ['conversation_id', 'user_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_participants_user'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_participants_conversation'), ['conversation_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_messages_conversation_time'), ['conversation_id', sa.literal_column('created_at DESC')], unique=False)
        batch_op.alter_column('conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
